/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AudioPlayer;
import Controller.GameController;
import Controller.EasyMode;
import Controller.MediumMode;
import Controller.HardMode;
import Controller.StrategyPattern;
import Controller.Circus;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Blu-Ray
 */
public class MainMenu extends javax.swing.JFrame {
    /**
     * Creates new form difficultyPage
     */
    public MainMenu() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        easyModeButton = new javax.swing.JButton();
        mediumModeButton = new javax.swing.JButton();
        hardModeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose a difficulty");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        easyModeButton.setBackground(new java.awt.Color(204, 102, 0));
        easyModeButton.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        easyModeButton.setForeground(new java.awt.Color(255, 255, 255));
        easyModeButton.setText("Easy");
        easyModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyModeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(easyModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 292, 67));

        mediumModeButton.setBackground(new java.awt.Color(204, 102, 0));
        mediumModeButton.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        mediumModeButton.setForeground(new java.awt.Color(255, 255, 255));
        mediumModeButton.setText("Medium");
        mediumModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumModeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(mediumModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 292, 67));

        hardModeButton.setBackground(new java.awt.Color(204, 102, 0));
        hardModeButton.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        hardModeButton.setForeground(new java.awt.Color(255, 255, 255));
        hardModeButton.setText("Hard");
        hardModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardModeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(hardModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 292, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghibli_circus.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 920, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyModeButtonActionPerformed
        GameController gameController;
        gameController = new GameController(() -> new Circus(800, 600, new EasyMode()));
        gameController.start();
        AudioPlayer audio = AudioPlayer.getInstance("C:\\Users\\Blu-Ray\\NetBeansProjects\\myGame2_3\\res\\easy_music.wav");
        audio.play();
        this.setVisible(false);
    }//GEN-LAST:event_easyModeButtonActionPerformed

    private void mediumModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumModeButtonActionPerformed

        GameController gameController;
        gameController = new GameController(() -> new Circus(800, 600, new MediumMode()));
        gameController.start();
        AudioPlayer audio = AudioPlayer.getInstance("C:\\Users\\Blu-Ray\\NetBeansProjects\\myGame2_3\\res\\medium_music.wav");
        audio.play();
        this.setVisible(false);
    }//GEN-LAST:event_mediumModeButtonActionPerformed

    private void hardModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardModeButtonActionPerformed

        GameController gameController;
        gameController = new GameController(() -> new Circus(800, 600, new HardMode()));
        gameController.start();
        AudioPlayer audio = AudioPlayer.getInstance("C:\\Users\\Blu-Ray\\NetBeansProjects\\myGame2_3\\res\\hard_music.wav");
        audio.play();
        this.setVisible(false);
    }//GEN-LAST:event_hardModeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyModeButton;
    private javax.swing.JButton hardModeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mediumModeButton;
    // End of variables declaration//GEN-END:variables
}
